### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by NGGNewGen** [Misteboss/TitlePE#10]
Class pocketmine\network\mcpe\protocol\SetTitlePacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by MalakasPlayzMC** [comment]
This plugin works only with the api3/network branch of GitHub.com/pmmp/PocketMine

**Comment by NGGNewGen** [comment]
So I have to download it from the API3 branch? okay sorry for the trouble haha

**Comment by MisteFr** [comment]
You need to use the api3\branch of pocketmine.
