### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mrpwes** [Misteboss/TitlePE#13]
![image](https://user-images.githubusercontent.com/31194909/40001264-708d839a-57c0-11e8-9846-eeaada720d04.png)
[Mon_May_14-21.45.39-AWST_2018.log](https://github.com/Misteboss/TitlePE/files/2000987/Mon_May_14-21.45.39-AWST_2018.log)

**Comment by MisteFr** [comment]
Hey @mrpwes !
Thanks for the report, I might update it to the latest PocketMine API this week.
